### ISSUE TITLE
support input fasta file directly?

### ISSUE THREAD

**Issue by BinhongLiu** [rochoa85/PepFun#2]
Hi, 
    Really nice tool!
    I found that the PepFun could perfectly deal with one sequence. I'm wondering if PepFun could support inputting a fasta file directly? If so, it could process many sequences at once and output a summary result table.
Thanks!

**Comment by rochoa85** [comment]
Hi Binhong

Thanks for asking and I am glad PepFun is been useful to you. Right now the cli only accepts a sequence as input. However, a loop can be generated to map multiple sequences. For version 2.0, which will be released in some months, this FASTA reading will be included together with other functionalities to cover more peptide analysis, and also to facilitate the usage of PepFun as a more stable module. I can let you know as soon as it gets released.

**Comment by BinhongLiu** [comment]
Great! Thank you!
